#!/usr/bin/env python
# vim:set ts=4 sw=4 et:
#
# Copyright 2015 UAVenture AG.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
# Updated: Tarek Taha : tarek.taha@kustar.ac.ae, Vladimir Ermakov
#    - Changed topic names after re-factoring : https://github.com/mavlink/mavros/issues/233
#    - Use mavros.setpoint module for topics

import rospy
import thread
import threading
import time
import mavros

import numpy as np

from math import *
from mavros.utils import *
from mavros import setpoint as SP
from std_msgs.msg import Header #type 
from std_msgs.msg import Float64, Float32 #type from msg generation
from geometry_msgs.msg import PoseStamped, Quaternion, TwistStamped #geometry
from tf.transformations import quaternion_from_euler #transformation
from mavros_msgs.srv import CommandLong #service_class
from sensor_msgs.msg import NavSatFix,Range,LaserScan #type
from teraranger_array.msg import RangeArray


class shadow_HIL:
    """
    This class sends position targets to FCU's position controller
    """
    def __init__(self):
        self.z = 1.8   
        self.armed = False  
        self.collective = RangeArray()
        self.rate = rospy.Rate(50) # 10hz is the original 
        self.sensor_0 = 0.0
        self.timeout = 180
        self.local_position = PoseStamped()
        self.count = 0
        self.counter = 0

        rospy.wait_for_service('mavros/cmd/arming', 30) # wait for arming, queue for 30s

        #rospy.Subscriber("subscribed topic",topic type,callback invoked with the message as the first arg)  

        rospy.Subscriber("hub_1/ranges_raw", RangeArray, self.hub_callback)
        rospy.Subscriber("mavros/local_position/pose", PoseStamped, self.position_callback)
        self.pub_spt = rospy.Publisher('mavros/setpoint_position/local', PoseStamped, queue_size=10)

        rospy.wait_for_service('mavros/cmd/command', 30)
        self._srv_cmd_long = rospy.ServiceProxy('mavros/cmd/command', CommandLong, persistent=True)
      
        while not rospy.is_shutdown(): #subsequent functions below are automatically run using this while loop (inert functions)  

            self.arm()

            print self.sensor_0 

            if self.sensor_0 <= 0.6 and self.local_position.pose.position.x > -2.0:
                self.deviance()
               
            elif self.sensor_0 <= 0.6 and self.local_position.pose.position.x <= -2.0:
                self.remain()

            else:
                self.origin()
                
            self.rate.sleep() #The loop calls rate.sleep(), which sleeps just long enough to maintain the desired rate through the loop.


    def hub_callback(self,msg): # callback invoked with the message as the first arg
        self.collective = msg
        for i in self.collective.ranges:
            self.sensor_0 = self.collective.ranges[0].range 

    def position_callback(self, data): # callback invoked with the message as the first arg
        self.local_position = data 

    def arm(self):
        if self.count < self.timeout:
            # FIXME: arm and switch to offboard
            # (need to wait the first few rounds until PX4 has the offboard stream)
            if not self.armed and self.count > 5:
                self._srv_cmd_long(False, 176, False,
                                   1, 6, 0, 0, 0, 0, 0)
                # make sure the first command doesn't get lost
                time.sleep(1)

                self._srv_cmd_long(False, 400, False,
                                   # arm
                                   1, 0, 0, 0, 0, 0, 0)

                self.armed = True
            self.count = self.count + 1
            self.rate.sleep() # The loop calls rate.sleep(), which sleeps just long enough to maintain the desired rate through the loop.

    def origin(self): 
        # Initialise necessary headers
        pos = PoseStamped()
        pos.header = Header() # initialising a new header for a new PoseStamped()
        pos.header.frame_id = "origin"
        pos.header.stamp = rospy.Time.now() # Update timestamp for each published SP

        # Establish desired setpoints
        pos.pose.position.x = 0.0 
        pos.pose.position.y = 0.0
        pos.pose.position.z = self.z

        # Establish desired orientation at setpoint
        roll_degrees = 0.0 
        roll = radians(roll_degrees)
        pitch_degrees = 0.0 
        pitch = radians(pitch_degrees)
        yaw_degrees = 0.0  
        yaw = radians(yaw_degrees)

        # Execute desired orientation
        quaternion = quaternion_from_euler(roll, pitch, yaw) #roll,pitch,yaw
        pos.pose.orientation = Quaternion(*quaternion)
        
        # Publishing to rostopic   
        self.pub_spt.publish(pos) # updated pose from pos.pose.orientation

    def deviance(self): 
        # Initialise necessary headers
        pos = PoseStamped()
        pos.header = Header() # initialising a new header for a new PoseStamped()
        pos.header.frame_id = "deviation"
        pos.header.stamp = rospy.Time.now() # Update timestamp for each published SP

        # Establish desired setpoints
        pos.pose.position.x = self.local_position.pose.position.x - 0.4
        pos.pose.position.y = self.local_position.pose.position.y 
        pos.pose.position.z = self.z

        # Establish desired orientation at setpoint
        roll_degrees = 0.0 
        roll = radians(roll_degrees)
        pitch_degrees = 0.0 
        pitch = radians(pitch_degrees)
        yaw_degrees = 0.0  
        yaw = radians(yaw_degrees)

        # Execute desired orientation
        quaternion = quaternion_from_euler(roll, pitch, yaw) #roll,pitch,yaw
        pos.pose.orientation = Quaternion(*quaternion)
        
        # Publishing to rostopic   
        self.pub_spt.publish(pos) # updated pose from pos.pose.orientation

    def remain(self): 
        # Initialise necessary headers
        pos = PoseStamped()
        pos.header = Header() # initialising a new header for a new PoseStamped()
        pos.header.frame_id = "remain"
        pos.header.stamp = rospy.Time.now() # Update timestamp for each published SP

        # Establish desired setpoints
        pos.pose.position.x = -2.0
        pos.pose.position.y = self.local_position.pose.position.y 
        pos.pose.position.z = self.z

        # Establish desired orientation at setpoint
        roll_degrees = 0.0 
        roll = radians(roll_degrees)
        pitch_degrees = 0.0 
        pitch = radians(pitch_degrees)
        yaw_degrees = 0.0  
        yaw = radians(yaw_degrees)

        # Execute desired orientation
        quaternion = quaternion_from_euler(roll, pitch, yaw) #roll,pitch,yaw
        pos.pose.orientation = Quaternion(*quaternion)
        
        # Publishing to rostopic   
        self.pub_spt.publish(pos) # updated pose from pos.pose.orientation    
    

if __name__ == '__main__':
    rospy.init_node('shadow_HIL_node', anonymous=True)

    node = shadow_HIL()

    rospy.spin()  # spin() simply keeps python from exiting until this node is stopped
     

